/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.ntt.controller;

import java.io.IOException;

import io.ntt.model.User;
import io.ntt.service.IService;
import io.ntt.service.UserService;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet(name = "App", urlPatterns = {"/"})
public class App extends HttpServlet {
    
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        IService<User> user_service = new UserService();
        User user = new User();
        user.setName("thinhorigamu");
        user.setEmail("nguyen.tien.thinh.thinhorigami@gmail.com");
        user.setPassword("123");
        user_service.add(user).ifPresentOrElse((o) -> {
            System.out.println("insert " + o.getEmail());
        }, () -> {
            System.out.println("insert falied");
        });
        resp.sendRedirect("/app/login");
    }
}
