/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.ntt.controller;

import io.ntt.lib.DataConnect;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        var s_f = new DataConnect();
        System.out.println(s_f.gitSessionFactory().toString());
    }
}
